Animal database
david30-maker/animal-database pull request #1
Opened 2023-05-15 22:35 UTC by david30-maker

- Use [this template](https://github.com/microverseinc/curriculum-template-databases) to generate your repo.
- Create a database named vet_clinic.
- Create a table named animals with the following columns:
-  >d: integer
-  >name: string
-  >date_of_birth: date
-  >escape_attempts: integer
-  >neutered: boolean
-  >weight_kg: decimal
- Copy the SQL you used in the previous point into the schema.sql file in the generated repository.
 - Insert the following data:
-  >Animal: His name is Agumon. He was born on Feb 3rd, 2020, and currently weighs 10.23kg. He was neutered and he has - 
 >never tried to escape.
-  >Animal: Her name is Gabumon. She was born on Nov 15th, 2018, and currently weighs 8kg. She is neutered and she has tried to escape 2 times.
-  >Animal: His name is Pikachu. He was born on Jan 7th, 2021, and currently weighs 15.04kg. He was not neutered and he has tried to escape once.
-  >Animal: Her name is Devimon. She was born on May 12th, 2017, and currently weighs 11kg. She is neutered and she has tried to escape 5 times.
- Copy the SQL you used in the previous point into the data.sql file in the generated repository.
- Write queries for the following quests:
-  >Find all animals whose name ends in "mon".
-  >List the name of all animals born between 2016 and 2019.
-  >List the name of all animals that are neutered and have less than 3 escape attempts.
-  >List the date of birth of all animals named either "Agumon" or "Pikachu".
-  >List name and escape attempts of animals that weigh more than 10.5kg
- Find all animals that are neutered.
- Find all animals not named Gabumon.
- Find all animals with a weight between 10.4kg and 17.3kg (including the animals with the weights that equals precisely 10.4kg or 17.3kg)

-Take a screenshot of the results of your queries.
-  []<img width="958" alt="image" src="https://github.com/david30-maker/animal-database/assets/95672514/ada48d3d-412b-4f05-bad5-8ad1624527b4">

2023-05-15 22:45 UTC, 1GORDON reviewed
##
## Hi @david30-maker ✋

Good job so far!

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

### This project will be marked as Invalid and won't affect the number of your weekly reviews.

- [ ] Could you customize your readme file properly with your own information? Remember to remove the live demo section and also add 1 to 3 features to your Future Features section.
- [ ] You may also add screenshots for all queries to your pull request summary. 

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@1GORDON` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-15 23:07 UTC, david30-maker commented
Thanks @1GORDON for reviewing my project, I will implement the required changes

2023-05-15 23:23 UTC, Davidosky007 reviewed
Hi @david30-maker 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has a generic readme template ,Kindly customize the readme to suit your project for example (project title, links should work etc) 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-05-16 01:25 UTC, david30-maker commented
Thanks @Davidosky007 for checking my project

2023-05-16 01:40 UTC, Shedrack-Sunday requested changes
Hello @david30-maker    👋 

# CHANGES REQUIRED ♻️

Great work on the project 👏
You've done well so far in the project,  However, there are a few you need to work on, to move to the next project. 💯

 
![](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)

## Highlights   
- Good use of GitHub features ✔️   
- Moderate use of SQL queries 👍 

  
# Required Changes  🌵 

- [x] You made some impressive implementations which I must say is a job well done. However, there are a few  features you missed

- In your README, you don't have a license file at the root, which is why your license file at the bottom is failing. kindly add the appropriate file path from the template provided 👍 

- You did not snap all the queries and include them in your PR. Seeing that you also missed two more queries, kindly make sure you add all screenshots of the query made as the next reviewer will check for those

_Check the comments for a detailed review 

# Optional suggestions 

Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-05-16 01:40 UTC, Shedrack-Sunday commented on queries.sql
> +SELECT name FROM animals WHERE date_of_birth BETWEEN '2016-01-01' AND '2019-12-13';
- [ ] Kindly correct the `2019` date to cover all dates of the year. it should be `2019/31/12';` instead 👍

2023-05-16 01:40 UTC, Shedrack-Sunday commented on queries.sql
> +SELECT * FROM animals WHERE name <> 'Gabumon';
- [ ] You missed two major queries here. Find the requirement screenshot below, and implement accordingly 👍 

## Missed query:
- ![image](https://github.com/david30-maker/animal-database/assets/50990925/522de1c0-1d0c-4cee-90ba-9a8378dbc912)
-  ![image](https://github.com/david30-maker/animal-database/assets/50990925/d9ba2574-9bbb-44cc-a758-1720807a0a40)

2023-05-16 06:24 UTC, david30-maker commented
Thanks @Shedrack-Sunday for reviewing my project, I will implement the required changes

2023-05-16 07:29 UTC, merged